apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: echo
spec:
  name: "echo"
  version: "1.0"
  description: "echo API"
  plans:
    - name: "KEY_LESS"
      description: "FREE"
      security: "KEY_LESS"
  proxy:
    virtual_hosts:
      - path: "/echo"
    groups:
      - endpoints:
          - name: "Default"
            target: "https://api.gravitee.io/echo"
